# Generated by Django 2.2.9 on 2020-01-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="demo",
            name="demotest",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
    ]
