# Generated by Django 2.2.9 on 2020-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_demo_demotest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Te',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('te', models.BinaryField()),
            ],
        ),
    ]
