# Generated by Django 2.2.9 on 2020-01-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_te'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
    ]
