# Generated by Django 2.2.9 on 2020-01-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_test"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="test",),
        migrations.AddField(
            model_name="user",
            name="dfs",
            field=models.GenericIPAddressField(blank=True, null=True, protocol="IPv4"),
        ),
    ]
