# Generated by Django 2.2.9 on 2020-01-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20200114_0835"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="dfs", new_name="test",),
    ]
