# Generated by Django 2.2.9 on 2020-01-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="testdata",
            field=models.CharField(blank=True, max_length=356, null=True),
        ),
    ]
