# Generated by Django 2.2.9 on 2020-01-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_testdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testdatademo',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
