# Generated by Django 2.2.9 on 2020-01-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_testdatademo"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="testdatademo",),
    ]
