# Generated by Django 2.2.9 on 2020-01-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_testdatademo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='demo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
