# Generated by Django 2.2.9 on 2020-01-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TestDemo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Testdemo1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tes", models.SmallIntegerField()),
            ],
        ),
    ]
