# Generated by Django 2.2.9 on 2020-01-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ui'),
    ]

    operations = [
        migrations.CreateModel(
            name='UITest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.EmailField(max_length=254)),
            ],
        ),
    ]
