# Generated by Django 2.2.9 on 2020-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_testmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="designData",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
