# Generated by Django 2.2.9 on 2020-01-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_customtext_designdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='titledesign',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
    ]
