# Generated by Django 2.2.9 on 2020-01-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200114_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
    ]
